### ISSUE TITLE
Subdomain hijacking?

### ISSUE THREAD

**Issue by anderspitman** [fasmide/remotemoe#1]
Hi there,

The readme mentions custom domains. Does remotemoe have any functionality to prevent subdomain hijacking on `remote.moe`?

**Comment by fasmide** [comment]
Yes it has - but not without caveats

When a connected user adds a hostname, remotemoe ties the custom domain and the user's public key together so no one else will be able to use it. 

However, remotemoe doesn't (yet - hopefully) do anything that prevents users from taking over each others `publickeyhash.remote.moe` subdomains that it creates pr default. This is of cause an issue I'm keen on fixing but I haven't really figured out a nice way of doing it. 

It's kind of hard for remotemoe to judge if this `randomstringofchoice.remote.moe` is actually a `publickeyhash.remote.moe` and if so should only be allowed if the public key matches. 

This kind of attack can only be carried out when the victim is offline - once the user with the actual publickey gets back online remotemoe will kick off the attacker - and it cannot be done when the victim is already connected

There is an easy fix though - just don't allow custom domains in the exact length of `<hash>.remote.moe` as the hashes are fixed in length - but I hope to come up with something better at some point - let me know what you think :)

btw - you are not limited to subdomains - if you have access to another domain's DNS you can point any domain to remotemoe and it will do its thing

**Comment by anderspitman** [comment]
Makes sense. Your solution seems like a reasonable approach. Maybe display a message if a user attempts to add a key of the exact length.

I like remotemoe. You've actually managed to add some unique useful features. I've added it to my list here: https://github.com/anderspitman/awesome-tunneling. Feel free to submit a PR if you want to change the wording or clarify at all.
