### ISSUE TITLE
WARNING: Server requests forwarding for unknown listen_port PORT

### ISSUE THREAD

**Issue by lem6ns** [fasmide/remotemoe#20]
Haven't received this error before it was offline.

PORT could be 80, 81, etc

**Comment by RennyDem** [comment]
Since this problem is already reported, I wanted to chime in and add that some of us get the following error: 
`$ WARNING: Server requests forwarding for unknown listen_port 80
WARNING: Server requests forwarding for unknown listen_port 80
WARNING: Server requests forwarding for unknown listen_port 80


`

**Comment by fasmide** [comment]
I'm guessing this change didn't see enough testing: https://github.com/fasmide/remotemoe/pull/18

I'm reverting the patch for now
